# Generated by Django 5.0.2 on 2024-02-10 18:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('estateobjects', '0001_squashed_0004_alter_estateobject_asking_price_and_more'), ('estateobjects', '0005_remove_store_position')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('collection_id', models.IntegerField()),
                ('creation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2012)])),
                ('creation_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('sale_date', models.DateField(blank=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('width_cm', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('height_cm', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('depth_cm', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('object_type', models.CharField(blank=True, choices=[('SC', 'Sculpture'), ('PA', 'Painting'), ('DR', 'Drawing'), ('OT', 'Other')], max_length=2)),
                ('object_material', models.CharField(blank=True, choices=[('ST', 'Steel'), ('BR', 'Bronze'), ('WO', 'Wood'), ('PA', 'Paper'), ('MI', 'Mixed'), ('OT', 'Other')], max_length=2)),
                ('object_state', models.CharField(blank=True, choices=[('PE', 'Perfect'), ('SD', 'Slightly deteriorated'), ('RE', 'Needs restoration'), ('NR', 'Non restorable')], max_length=2)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reserved_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('estate_object', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estateobjects.estateobject')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('collection_id', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('store_type', models.CharField(choices=[('BO', 'Box'), ('RO', 'Room'), ('BU', 'Building'), ('OU', 'Outside')], max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estateobjects.store')),
            ],
        ),
        migrations.AddField(
            model_name='estateobject',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estateobjects.store'),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='creation_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='creation_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2012)]),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='depth_cm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='width_cm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
