# Generated by Django 5.0.2 on 2024-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateobjects', '0006_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('email_address', models.CharField(max_length=512)),
                ('post_address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='estateobject',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='estateobject',
            name='reserved_for',
        ),
    ]
