# Generated by Django 5.0.2 on 2024-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateobjects', '0009_alter_estateobject_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='collection_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
