# Generated by Django 5.0.2 on 2024-02-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateobjects', '0011_estateobject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateobject',
            name='object_material',
            field=models.CharField(blank=True, choices=[('SL', 'Steel'), ('BR', 'Bronze'), ('AL', 'Aluminium'), ('WO', 'Wood'), ('PA', 'Paper'), ('SN', 'Stone'), ('CE', 'Ceramic'), ('MI', 'Mixed'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='object_type',
            field=models.CharField(blank=True, choices=[('SC', 'Sculpture'), ('PA', 'Painting'), ('DR', 'Drawing'), ('MA', 'Maquette'), ('OT', 'Other')], max_length=2),
        ),
    ]
